### ISSUE TITLE
Query parameters converted to string, therefore e.g. limit (int) parameter not working

### ISSUE THREAD

**Issue by Flarescape** [sebastienros/fluid#193]
**Setup:**
MSSQL DB
OC RC2-13391 (current nigthly dev)

```liquid
{% assign blogPosts = Queries.FilterBlogPostsByBlog | query: blogname:'News', limit:1 %}
{% for bpost in blogPosts %}
{{bpost}}
{% endfor %}
```

**Query:**
```sql
Select cpi.DocumentId 
from ContainedPartIndex cpi 
inner join ContentItemIndex cii on cpi.ListContentItemId = cii.ContentItemId
where cii.DisplayText like @blogname
order by cpi.DocumentId
limit @limit:0
```
Query is working as expected when running it with the same parameters directly from the query editor.

**Error:**
```OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay|ERROR|Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by SqlException Microsoft.Data.SqlClient.SqlException (0x80131904): The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer.```

**Comment by sebastienros** [comment]
Nothing says that it's an issue with fluid. I will test on oc.

**Comment by Flarescape** [comment]
Alright, thank you and I'm sorry! Should i move it?
My thought was, that it's maybe not correct in this case, that all parameter values are casted to string.

**Comment by Flarescape** [comment]
Maybe the stack trace from the log file helps:
```
2020-06-08 13:43:33.8462|countit_jobs||e85cde3-4ceef4aa853bf9ee.||OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay|ERROR|Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by SqlException Microsoft.Data.SqlClient.SqlException (0x80131904): The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419
   at OrchardCore.Queries.Sql.SqlQuerySource.ExecuteQueryAsync(Query query, IDictionary`2 parameters) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Queries\Sql\SqlQuerySource.cs:line 91
   at OrchardCore.Queries.Liquid.QueryFilter.ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext ctx) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Queries\Liquid\QueryFilter.cs:line 34
   at Fluid.Ast.FilterExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.AssignStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.BaseFluidTemplate`1.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, List`1 statements, Int32 startIndex)
   at Fluid.FluidTemplateExtensions.<RenderAsync>g__Awaited|3_0(ValueTask task, StringWriter writer, StringBuilderPool builder)
   at OrchardCore.DisplayManagement.Liquid.LiquidViewTemplateExtensions.RenderAsync(LiquidViewTemplate template, TextEncoder encoder, LiquidTemplateContext context, Object model, Action`1 scopeAction) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\LiquidViewTemplate.cs:line 218
   at OrchardCore.Liquid.Services.LiquidShapes.BuildViewModelAsync(ShapeDisplayContext shapeDisplayContext) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Liquid\Services\LiquidShapes.cs:line 24
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 133
ClientConnectionId:d11b8c72-3b22-4b44-929c-214259e17618
Error Number:1060,State:1,Class:15    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419
   at OrchardCore.Queries.Sql.SqlQuerySource.ExecuteQueryAsync(Query query, IDictionary`2 parameters) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Queries\Sql\SqlQuerySource.cs:line 91
   at OrchardCore.Queries.Liquid.QueryFilter.ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext ctx) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Queries\Liquid\QueryFilter.cs:line 34
   at Fluid.Ast.FilterExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.AssignStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.BaseFluidTemplate`1.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, List`1 statements, Int32 startIndex)
   at Fluid.FluidTemplateExtensions.<RenderAsync>g__Awaited|3_0(ValueTask task, StringWriter writer, StringBuilderPool builder)
   at OrchardCore.DisplayManagement.Liquid.LiquidViewTemplateExtensions.RenderAsync(LiquidViewTemplate template, TextEncoder encoder, LiquidTemplateContext context, Object model, Action`1 scopeAction) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\LiquidViewTemplate.cs:line 218
   at OrchardCore.Liquid.Services.LiquidShapes.BuildViewModelAsync(ShapeDisplayContext shapeDisplayContext) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Liquid\Services\LiquidShapes.cs:line 24
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 133

```

**Comment by sebastienros** [comment]
If it's still current, this should be filed in OC.
